config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:index] do
    resources :click_tracks, only: [:index]
  end
  
  namespace :api do
    resources :items, only: [] do
      resources :click_tracks, only: [:create] do
        collection do
          get 'by_day'
        end
      end
    end
  end
    
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click_track.rb
class ClickTrack < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :click_tracks
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  before_action :load_data
  before_action :format_dates
  
  def create
    respond_to do |format|
      format.js
    end
  end

  
  private
    
    def load_data
      @item = Item.includes(:click_tracks).find_by(id: params[:item_id])
      @click_tracks = @item.click_tracks
    end
    
    def format_dates
      @start_date = params[:start_date].nil? || params[:start_date].empty? ?
          1.month.ago.midnight :
          params[:start_date].to_datetime.midnight
      @end_date = params[:end_date].nil? || params[:end_date].empty? ?
          Time.current.at_end_of_day :
          params[:end_date].to_datetime.at_end_of_day
      @start_date, @end_date = @end_date, @start_date if @end_date < @start_date
    end
    
    def by_year?
      @end_date - (1.year + 2.days) > @start_date
    end
    
    def by_month?
      @end_date - (3.month + 2.days) > @start_date
    end  
end

app/controllers/api/click_tracks_controller.rb
class Api::ClickTracksController < Api::BaseController
  def create
    respond_to do |format|
      format.js
    end
  end  
  
  def by_day
    opts = ['created_at', {range: @start_date..@end_date, format: '%d %b'}]
    method_name = :group_by_day
    if by_year?
      opts[1].merge!({format: '%Y'})
      method_name = :group_by_year
    elsif by_month?
      opts[1].merge!({format: '%b %Y'})
      method_name = :group_by_month
    end
    clicks = @click_tracks.send(method_name, *opts).count
    render json: [{name: 'Click count', data: clicks}].chart_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/click_tracks_controller.rb
class ClickTracksController < ApplicationController
  def index
    @item = Item.find_by(id: params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/click_tracks_helper.rb
module ClickTracksHelper
  def stat_by(start_date, end_date)
    start_date ||= 1.month.ago
    end_date   ||= Time.current
    line_chart by_day_api_item_click_tracks_path(@item, start_date: start_date, end_date: end_date),
             basic_opts('Click count', start_date, end_date)
  end
  private
  
  def basic_opts(title, start_date, end_date)
    {
      discrete: true,
      library: {
        title: {text: title, x: -20},
        subtitle: {text: "from #{l(start_date, format: :medium)} to #{l(end_date, format: :medium)}", x: -20},
        yAxis: {
          title: {
            text: 'Count'
          }
        },
        tooltip: {
          valueSuffix: 'click(s)'
        },
        credits: {
          enabled: false
        }
      }
    }
  end
end

app/views/click_tracks/_graph.html.erb
<div id="graph">
  <%= stat_by(@start_date, @end_date) %>
</div>

app/views/click_tracks/index.html.erb
<h1>Click tracking</h1>

<div id="event_period" class="row">
  <%= form_tag api_item_click_tracks_path(@item), remote: true do %>
    <div class="col-sm-1">
      <label for="start_date">Start date</label>
    </div>

    <div class="col-sm-3">
      <div class="input-group">
        <input type="text" class="actual_range form-control datepicker" id="start_date" name="start_date">
        <div class="input-group-addon">
          <span class="glyphicon glyphicon-th"></span>
        </div>
      </div>
    </div>

    <div class="col-sm-1 col-sm-offset-1">
      <label for="end_date">End date</label>
    </div>

    <div class="col-sm-3">
      <div class="input-group">
        <input type="text" class="actual_range form-control datepicker" id="end_date" name="end_date">
        <div class="input-group-addon">
          <span class="glyphicon glyphicon-th"></span>
        </div>
      </div>
    </div>

    <div class="col-sm-2">
      <%= submit_tag 'Show!', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<%= render 'graph' %>

<script data-turbolinks-track>
  $(document).ready(function() {
    $('#event_period').datepicker({
      inputs: $('.actual_range'),
      startDate: '-3y',
      endDate: '0d',
      todayBtn: 'linked',
      todayHighlight: 'true',
      format: 'yyyy-mm-dd'
    });
  });
</script>

app/views/items/_item.html.erb
<li>
  <%= item.title %>
  <%= link_to 'View clicks', item_click_tracks_path(item), class: 'btn btn-primary' %>
</li>

app/views/items/index.html.erb
<h1>Items</h1>

<ul><%= render @items %></ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackerByChartkick</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>